-- SafeSandesh Supabase schema.
-- Run this once in the Supabase SQL editor before switching SCAN_DB_BACKEND to "supabase".
-- Use a server-side Streamlit secret with SUPABASE_SERVICE_ROLE_KEY for this prototype.

create table if not exists public.scans (
    id bigint generated by default as identity primary key,
    ts text not null,
    scan_date text not null default '',
    scan_time text not null default '',
    scan_datetime_local text not null default '',
    scan_timezone text not null default '',
    language text not null,
    label text not null,
    scam_type text not null,
    risk_score integer not null,
    model_confidence double precision not null default 0.0,
    model_source text not null default 'unknown',
    model_version text not null default 'unknown',
    type_source text not null default 'unknown',
    reason text not null default '',
    message text not null default '',
    comparison_label text not null default 'unknown',
    comparison_scam_type text not null default 'Other',
    comparison_risk_score integer not null default 0,
    comparison_model_confidence double precision not null default 0.0,
    comparison_model_source text not null default 'unknown',
    comparison_model_version text not null default 'unknown',
    comparison_type_source text not null default 'unknown',
    comparison_tertiary_label text not null default 'unknown',
    comparison_tertiary_scam_type text not null default 'Other',
    comparison_tertiary_risk_score integer not null default 0,
    comparison_tertiary_model_confidence double precision not null default 0.0,
    comparison_tertiary_model_source text not null default 'unknown',
    comparison_tertiary_model_version text not null default 'unknown',
    comparison_tertiary_type_source text not null default 'unknown',
    review_recommended boolean not null default false,
    review_reason text not null default '',
    final_score_method text not null default 'primary_model',
    model_outputs_json text not null default ''
);

create index if not exists scans_ts_idx on public.scans (ts desc);
create index if not exists scans_language_idx on public.scans (language);
create index if not exists scans_label_idx on public.scans (label);
create index if not exists scans_scam_type_idx on public.scans (scam_type);

alter table public.scans enable row level security;

grant usage on schema public to service_role;
grant all on table public.scans to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.reset_safesandesh_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    scan_max bigint;
begin
    select coalesce(max(id), 0) into scan_max from public.scans;
    perform setval(pg_get_serial_sequence('public.scans', 'id'), greatest(scan_max, 1), scan_max > 0);
end;
$$;

grant execute on function public.reset_safesandesh_identity_sequences() to service_role;

-- Do not add public anon SELECT policies if you store full user messages.
-- The Streamlit server should read/write through its private service-role secret.
